/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f429xx_gpio_driver.h"

void delay(void);
void LNH_GPIOCLK(GPIO_RegDef_t*pGPIOx, uint8_t EN_DI);
void LNH_GPIO_Init(void);
int main(void)
{


	LNH_GPIOCLK(GPIOG,1);
	LNH_GPIOCLK(GPIOA,1);


	LNH_GPIO_Init();

	GPIO_IRQ_ITConfig(IRQ_NO_EXTI0,EN);
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI0,1);
	while(1)
	{
		/*if(__LNH_GPIO_ReadPin(GPIOA, GPIO_PIN_0) == 1)
		{
			delay();
			__LNH_GPIO_TogglePin(GPIOG, GPIO_PIN_14);
		}
		delay();*/
	}
}


void LNH_SysCLK(GPIO_RegDef_t*pGPIOx, uint8_t EN_DI)
{
	__LNH_GPIO_PeriClockControl(pGPIOx,EN_DI);
}


void LNH_GPIO_Init(void)
{
	GPIO_Config_t pGPIOConfig1;
	pGPIOConfig1.pGPIOx = GPIOG;
	pGPIOConfig1.GPIO_PIN = GPIO_PIN_14;
	pGPIOConfig1.GPIO_MODE = GPIO_MODE_OUT;
	pGPIOConfig1.GPIO_SPEED = GPIO_SPEED_MS;
	pGPIOConfig1.GPIO_PUPD = GPIO_PUPD_NP;
	pGPIOConfig1.GPIO_OTYPE = GPIO_OTYPE_PP;
	pGPIOConfig1.GPIO_AF = 0;
	pGPIOConfig1.pEXTI = EXTI;
	pGPIOConfig1.pSYSCFG = SYSCFG;
	pGPIOConfig1.EXTI_ENDI = EXTI_DI;
	pGPIOConfig1.EXTI_TRIGGER = 0;
	__LNH_GPIO_Init(&pGPIOConfig1);
	GPIO_Config_t pGPIOConfig2;
	pGPIOConfig2.pGPIOx = GPIOA;
	pGPIOConfig2.GPIO_PIN = GPIO_PIN_0;
	pGPIOConfig2.GPIO_MODE = GPIO_MODE_IN;
	pGPIOConfig2.GPIO_SPEED = GPIO_SPEED_MS;
	pGPIOConfig2.GPIO_PUPD = GPIO_PUPD_PD;
	pGPIOConfig2.GPIO_OTYPE = GPIO_OTYPE_PP;
	pGPIOConfig2.GPIO_AF = 0;
	pGPIOConfig2.pEXTI = EXTI;
	pGPIOConfig2.pSYSCFG = SYSCFG;
	pGPIOConfig2.EXTI_ENDI = EXTI_EN;
	pGPIOConfig2.EXTI_TRIGGER = EXTI_IT_RT;

	__LNH_GPIO_Init(&pGPIOConfig2);
}


void delay()
{

		for(uint32_t i=0;i<500000/2;i++);

}
void EXTI0_IRQHandler(void)
{
	__LNH_GPIO_IRQHanding(GPIO_PIN_0);
	__LNH_GPIO_TogglePin(GPIOG, GPIO_PIN_14);
}
